---
apt_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - gcc
  - gnupg2
  - python-is-python3
  - python3-pip
  - software-properties-common
  - sudo
  - tmux
  - wget
  - systemd
  - nfs-common
pip_packages:
  - networkx
  - nltk
  - psutil
  - wheel
  - bcrypt==4.1.0
  - netaddr
