---
apt_packages:
  - apt-transport-https
  - build-essential
  - ca-certificates
  - curl
  - gcc
  - gnupg2
  - maven
  - openjdk-11-jdk
  - python-is-python3
  - python3-pip
  - redis-server
  - redis
  - software-properties-common
  - sudo
  - tmux
  - wget

pip_packages:
  - dash
  - icecream
  - matplotlib
  - networkx
  - nltk
  - notebook
  - numpy
  - pandas
  - psutil
  - redis
  - scikit-learn
  - scipy
  - wheel
  - wordcloud
